### ISSUE TITLE
Rails hard dependency?

### ISSUE THREAD

**Issue by josemotanet** [littlelines/media_embed#2]
Hello,

I'm wondering why you guys require Rails as a hard dependency in your gemspec. It's definitely not the case and it makes for a more rigid dependency management situation. Are you willing to let the dependency go and wire Rails in a different way?

Let me know, I'm open to help on this.

**Comment by HazelGrant** [comment]
Thanks again for the work you put into this! I'm planning to release the next version this afternoon.
