### ISSUE TITLE
options not passed on in rubygems version

### ISSUE THREAD

**Issue by jmtoball** [littlelines/media_embed#4]
Hello and thank you for this handy gem!
When I tried to use it I found it didn't forward the options. When I wanted to submit a PR for this, I noticed that in master it is already fixed with 7f518cc820c1ae5883ec6e863d054fb17d75435c. However, the fix is not released to rubygems. Can you prepare a release for the current master? It seems to be working fine.
Thanks!

**Comment by HazelGrant** [comment]
Hi! I've released the next version, both with the options ability and with a helpful PR that removed Rails as a required dependency. Everything else should work the same as before, however. I'm glad you've found this gem handy. :)
